// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ-Z6-7vLVHhQs-baFrUp1QvkaOaXFfnk',
    appId: '1:269375733952:web:36e29b42067c90dcd72d25',
    messagingSenderId: '269375733952',
    projectId: 'flutterdemo-8d638',
    authDomain: 'flutterdemo-8d638.firebaseapp.com',
    databaseURL: 'https://flutterdemo-8d638-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemo-8d638.appspot.com',
    measurementId: 'G-4F90V4GM00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQoNLGuOS_JzA2Fvr59jU5_5FmFRbi8mU',
    appId: '1:269375733952:android:82febc610200ddfbd72d25',
    messagingSenderId: '269375733952',
    projectId: 'flutterdemo-8d638',
    databaseURL: 'https://flutterdemo-8d638-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemo-8d638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKC5zxoCL9QKJYczr8BxmG9uzPMhkC9ZY',
    appId: '1:269375733952:ios:c4e38273c24f5da3d72d25',
    messagingSenderId: '269375733952',
    projectId: 'flutterdemo-8d638',
    databaseURL: 'https://flutterdemo-8d638-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemo-8d638.appspot.com',
    androidClientId: '269375733952-ommmc1g219stg5j630sd24c53oquvg0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopii2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKC5zxoCL9QKJYczr8BxmG9uzPMhkC9ZY',
    appId: '1:269375733952:ios:d2c67c9b55d2e177d72d25',
    messagingSenderId: '269375733952',
    projectId: 'flutterdemo-8d638',
    databaseURL: 'https://flutterdemo-8d638-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemo-8d638.appspot.com',
    androidClientId: '269375733952-ommmc1g219stg5j630sd24c53oquvg0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopii2.RunnerTests',
  );
}
